In [2]:
import numpy as np
import pandas as pd
from kmodes.kmodes import KModes

In [3]:
data = np.random.choice(20, (100, 10))

In [4]:
data

array([[18,  3, 14, 17,  9,  7,  2,  1, 14, 18],
       [ 9,  0, 19, 13,  4,  6,  6, 11, 13, 18],
       [17, 12,  2,  8,  6, 10,  8,  4, 15,  5],
       [ 8,  9,  1,  3, 19,  9, 19, 17,  7,  0],
       [12,  5,  7,  5,  6, 12,  4, 12,  8,  4],
       [10,  2, 15,  5,  8, 17,  7, 10,  5, 19],
       [ 0,  3, 11,  4,  8, 13,  1,  9, 12, 19],
       [18,  9, 19, 11, 17, 14, 14,  6, 18,  1],
       [12, 18, 14,  9,  7,  8,  3, 11,  7,  9],
       [17,  2, 11, 15,  0,  6, 19,  1,  9,  9],
       [ 7,  6, 13,  6, 14, 14,  3,  7,  3,  6],
       [13, 11, 16,  8, 14,  5, 17, 12,  1,  1],
       [18,  8,  7,  1,  1,  0, 16,  3,  6, 11],
       [16, 11,  5, 13,  1,  4,  5, 13, 13,  7],
       [ 7,  0,  4, 14,  4, 11, 14, 16,  8,  8],
       [11, 15,  6,  4, 14,  0, 10,  7,  4,  7],
       [18, 13,  1, 13, 17,  3, 15, 11, 15,  9],
       [ 7,  0,  8,  8,  8, 19, 18,  1,  2,  5],
       [ 1, 12,  5,  8, 12, 19,  3, 10,  2, 18],
       [ 5, 10,  4,  9,  6,  4, 13,  0, 18,  7],
       [11,  0,  4, 12,  4, 10, 16, 15, 18, 16],
       [10, 14,  7, 12, 19,  5, 14,  8, 11,  5],
       [16, 14,  1,  7,  2,  8, 17, 11, 19, 13],
       [ 5,  4, 13,  1, 15,  6, 19, 16, 14,  4],
       [10,  8,  0, 12, 10, 17, 17,  4, 10,  9],
       [16,  9, 13,  6,  1, 11,  4,  2, 15, 15],
       [ 7, 15, 13, 10, 11, 13,  0, 15,  0,  2],
       [ 5,  8,  0,  8,  1, 14, 14, 16,  0, 12],
       [ 5, 17,  7,  2, 17, 16,  3,  7,  5, 12],
       [12, 11, 14, 13, 14, 19, 14,  0,  9,  0],
       [13,  3, 13, 19, 10, 11, 13,  4,  2,  7],
       [ 0, 18,  8, 18,  2,  2,  3, 18,  0,  6],
       [ 6,  8, 14,  2, 12, 12, 17, 17,  1,  4],
       [14, 11,  0, 10, 10,  4,  5, 14,  4, 11],
       [14, 13,  2,  3,  7,  8, 16,  7, 10,  0],
       [ 0,  4,  2, 18,  9, 11,  5,  5,  8, 11],
       [13,  8,  0, 13,  5, 19, 11,  0, 12, 16],
       [ 7, 10,  4,  7,  2,  1, 16, 19, 15,  8],
       [ 4, 19,  0,  7, 12, 11,  5,  7, 13, 13],
       [14,  6,  4,  5,  2,  2,  6, 14, 13, 18],
       [12,  3, 19,  2, 12,  2,  0, 16, 13, 10],
       [ 6,  6, 12, 16, 13,  6, 17, 18,  9,  9],
       [12, 19,  9, 15, 11, 11,  9,  8, 12,  6],
       [15,  7,  5,  9,  4, 19, 12, 18,  1, 17],
       [ 4, 19,  2, 19,  3, 17, 14, 19,  5,  5],
       [ 4, 13, 12,  7,  7,  6,  4,  1, 11,  0],
       [17, 18, 15, 11, 12,  2,  4, 16,  0,  3],
       [ 3,  8, 16, 19, 11,  1,  9, 19,  1,  9],
       [ 3, 19,  1,  7, 14, 13,  1, 18,  9, 15],
       [16,  3, 16,  0, 19,  2,  2, 12, 10, 11],
       [ 1, 19, 16, 17,  7, 19, 12, 19,  7,  0],
       [17, 12,  3, 15,  4,  5, 14,  8,  9,  9],
       [18,  8,  3,  3,  9, 17,  9, 12,  6,  7],
       [ 0,  3, 17,  3, 10, 13,  1,  9,  4, 18],
       [ 4, 10,  8, 16,  6,  8, 14,  6, 11, 17],
       [14, 15,  3, 17,  6,  8, 19, 11,  1, 13],
       [ 8,  9,  5,  5, 17,  9, 15, 19,  9,  0],
       [ 6, 12, 19, 12,  9, 10, 13, 10, 15, 17],
       [ 9,  6, 12, 14,  5, 10,  0,  7,  7,  6],
       [17,  8,  6,  0,  8,  6,  6,  6,  1,  6],
       [ 4, 19, 19, 11,  8, 10,  8,  1,  7, 16],
       [13, 18, 12,  4,  8, 19, 13,  5, 10, 14],
       [10, 19,  5,  6, 19, 18,  5,  3, 10,  5],
       [ 7, 13, 13, 15, 11,  8,  9,  9, 14,  6],
       [ 3, 11,  5, 12,  0,  9, 11,  4, 11, 12],
       [ 9, 10, 17, 14, 17,  5, 14,  4,  3,  9],
       [12,  8, 17, 12, 19, 16,  1, 18, 13,  2],
       [ 3, 17, 13,  0, 16, 10,  8, 10,  1,  9],
       [12,  3, 13,  6,  8,  1,  8, 12,  3, 12],
       [ 7, 17, 17,  3, 19,  3,  3,  2,  3,  4],
       [19, 14,  8, 17,  8,  8, 17, 11, 19,  1],
       [ 8, 10,  0, 17,  8,  3,  2,  7,  4,  2],
       [ 9,  9,  5,  1, 16,  4,  2,  4,  5,  6],
       [15, 18,  7,  6, 17, 11,  1, 16, 13, 15],
       [15, 13, 14,  3, 12, 13,  1,  5,  1, 10],
       [11,  8,  4, 11,  3,  1,  7,  8, 17,  1],
       [13,  5, 15,  7,  7, 15, 19,  4, 12,  7],
       [ 8, 18, 19, 10, 16, 14, 10, 12,  5,  7],
       [10, 15, 15,  8, 19,  8,  8,  8,  2, 14],
       [ 8, 19, 18, 12, 11, 15, 13,  9, 16,  3],
       [ 6,  9, 11,  8,  6,  5, 11,  4, 16, 15],
       [ 6, 10,  6,  0,  5,  5, 13,  5, 15, 11],
       [15, 14,  8,  8, 10,  5,  4, 15,  2, 13],
       [11,  0, 13,  9, 18, 11, 11, 16,  8,  5],
       [17,  3,  1,  4, 15,  7, 14, 19,  5, 16],
       [ 2, 15, 17, 17, 18, 15, 10, 19,  4, 16],
       [17, 10,  9,  7, 14, 16,  2,  0, 12,  0],
       [10, 11, 18,  4,  8, 16, 12,  7, 17, 10],
       [ 7,  1,  5,  6,  2, 11,  2, 18,  0, 17],
       [ 9, 13, 11,  5, 19,  5,  0,  4,  3, 18],
       [13,  9, 10, 11,  1,  3, 13, 17, 18, 15],
       [ 8,  0, 14, 11,  7, 16,  1,  7, 18, 19],
       [12, 14,  9, 15,  9, 19, 16, 15, 10, 12],
       [ 6,  1,  4, 11, 12,  2,  9, 15,  3,  9],
       [ 3,  2, 15,  3, 17, 13,  4,  3, 19,  9],
       [ 4, 12,  5,  8, 16, 14,  1,  7,  7,  7],
       [ 4, 19, 12,  8,  8, 16,  9, 17,  3,  6],
       [ 1,  3, 14, 11,  8, 12, 16,  1,  0,  2],
       [10, 17,  0,  0,  4,  5,  1,  6,  1, 12],
       [18, 14,  9, 14, 11,  6, 13, 13, 14,  9]])

In [5]:
dataset = pd.DataFrame({'a': data[:, 0], 'b': data[:, 1], 'c': data[:, 2], 'd': data[:, 3], 'e': data[:, 4], 'f': data[:, 5], 'g': data[:, 6], 'h': data[:, 7], 'i': data[:, 8], 'j': data[:, 9]})

In [6]:
dataset

     a   b   c   d   e   f   g   h   i   j
0   18   3  14  17   9   7   2   1  14  18
1    9   0  19  13   4   6   6  11  13  18
2   17  12   2   8   6  10   8   4  15   5
3    8   9   1   3  19   9  19  17   7   0
4   12   5   7   5   6  12   4  12   8   4
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
95   4  12   5   8  16  14   1   7   7   7
96   4  19  12   8   8  16   9  17   3   6
97   1   3  14  11   8  12  16   1   0   2
98  10  17   0   0   4   5   1   6   1  12
99  18  14   9  14  11   6  13  13  14   9

[100 rows x 10 columns]

In [24]:
km = KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)

In [26]:
clusters = km.fit_predict(data)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 18, cost: 822.0
Run 1, iteration: 2/100, moves: 8, cost: 819.0
Run 1, iteration: 3/100, moves: 1, cost: 819.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 23, cost: 830.0
Run 2, iteration: 2/100, moves: 1, cost: 830.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 19, cost: 823.0
Run 3, iteration: 2/100, moves: 0, cost: 823.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 15, cost: 824.0
Run 4, iteration: 2/100, moves: 3, cost: 824.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 14, cost: 829.0
Run 5, iteration: 2/100, moves: 6, cost: 829.0
Best run was number 1

In [28]:
kmodes = km.cluster_centroids_
shape = kmodes.shape

In [32]:
print(kmodes)

[[ 8  1  2  0  3  8  6 19  9  4]
 [ 6  4 19 14  0  0 12  6  5  5]
 [15  2 13  6 18  7  0  4 14  0]]

In [29]:
for i in range(shape[0]):
    if sum(kmodes[i,:]) == 0:
        print("\ncluster " + str(i) + ": ")
        print("no-skills cluster")
    else:
        print("\ncluster " + str(i) + ": ")
        cent = kmodes[i,:]
        for j in dataset.columns[np.nonzero(cent)]:
            print(j)

cluster 0:
a
b
c
e
f
g
h
i
j

cluster 1:
a
b
c
d
g
h
i
j

cluster 2:
a
b
c
d
e
f
h
i

In [18]:
km

KModes(cat_dissim=<function matching_dissim at 0x7f1b66d27dd0>, init='Huang',
       max_iter=100, n_clusters=3, n_init=5, n_jobs=1, random_state=None,
       verbose=1)

In [ ]:
km.